In [1]:
import numpy as np

In [2]:
arr = np.random.rand(4)
arr

array([0.80765517, 0.87900542, 0.20359793, 0.73711195])

`sorting`

In [4]:
sorted_arr = np.sort(arr)
sorted_arr

array([0.20359793, 0.73711195, 0.80765517, 0.87900542])

In [7]:
rev_arr = -np.sort(-arr)
rev_arr

array([0.87900542, 0.80765517, 0.73711195, 0.20359793])

In [8]:
arr2d = np.random.rand(3, 4)
arr2d

array([[0.02426452, 0.1955352 , 0.46477296, 0.70016683],
       [0.17929517, 0.14822668, 0.00172569, 0.79589725],
       [0.90657767, 0.32375686, 0.44213178, 0.05741749]])

In [9]:
row_sorted = np.sort(arr2d, axis=1)
row_sorted

array([[0.02426452, 0.1955352 , 0.46477296, 0.70016683],
       [0.00172569, 0.14822668, 0.17929517, 0.79589725],
       [0.05741749, 0.32375686, 0.44213178, 0.90657767]])