In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('data.npy', arr)

In [6]:
arr2 = np.load('data.npy')
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1 = np.arange(20)
np.savez('arrays', a=arr, b=arr1)

In [13]:
arrays = np.load('arrays.npz')
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez_compressed('arrays_compressed', a=arr, b=arr1)

In [16]:
c_arrays = np.load('arrays_compressed.npz')
c_arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])