In [1]:
import numpy as np

In [2]:
data1 = [3.5, 5, 6, 2] # list
arr1 = np.array(data1) # array1

In [3]:
data1

[3.5, 5, 6, 2]

In [4]:
arr1

array([3.5, 5. , 6. , 2. ])

In [5]:
data2 = (4, 5, 3.2, 7)
arr2 = np.array(data2) # array2

In [7]:
arr2

array([4. , 5. , 3.2, 7. ])

In [8]:
arr1.ndim # number of dimensions

1

In [9]:
arr2.ndim

1

In [10]:
data3 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # nested list
arr3 = np.array(data3) # array3

In [11]:
data3

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
arr3.ndim

2

In [32]:
data4 = [[[1, 2], [3, 4]], 
         [[5, 6], [7, 8]], 
         [[9, 10], [11, 12]]] # nested list with 3 levels
arr4 = np.array(data4) # array4

In [29]:
arr4.ndim

3

In [30]:
arr4.shape

(3, 2, 2)

In [34]:
arr4.size

12

In [35]:
arr5 = np.zeros((2, 3)) # 2 rows, 3 columns
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
arr6 = np.ones((3, 4)) # 3 rows, 4 columns
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
arr7 = np.arange(4, 20, 2) # 1D array from 4 to 20 with step 2
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
arr7.ndim 

1