In [7]:
import numpy as np

In [8]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.square(arr) # square of each element

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.exp(arr)  # e^arr

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [13]:
np.log(arr)  # natural logarithm

C:\Users\muzaf\AppData\Local\Temp\ipykernel_5664\3309670735.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)  # natural logarithm


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr2 = np.random.randn(6) # array of 6 random numbers from standard normal distribution
arr2

array([ 0.69804547, -0.35102855,  1.69745915, -0.08664782,  0.76131236,
        0.79689282])

In [16]:
remainder, whole_part = np.modf(arr2) # split into fractional and integer parts

In [17]:
print(remainder)
print(whole_part)

[ 0.69804547 -0.35102855  0.69745915 -0.08664782  0.76131236  0.79689282]
[ 0. -0.  1. -0.  0.  0.]


In [18]:
np.sign(arr2)  # sign function

array([ 1., -1.,  1., -1.,  1.,  1.])

In [19]:
np.isnan(arr2)  # check for NaN values

array([False, False, False, False, False, False])

In [20]:
arr2[0] = np.nan
arr2

array([        nan, -0.35102855,  1.69745915, -0.08664782,  0.76131236,
        0.79689282])

In [21]:
np.isnan(arr2)

array([ True, False, False, False, False, False])

### 1. Math Operations
| Function | Description |
| :--- | :--- |
| `add(x1, x2)` | Add arguments element-wise. |
| `subtract(x1, x2)` | Subtract arguments element-wise. |
| `multiply(x1, x2)` | Multiply arguments element-wise. |
| `divide(x1, x2)` | Returns a true division of the inputs, element-wise. |
| `logaddexp(x1, x2)` | Logarithm of the sum of exponentiations of the inputs. |
| `logaddexp2(x1, x2)` | Logarithm of the sum of exponentiations of the inputs in base-2. |
| `true_divide(x1, x2)` | Returns a true division of the inputs, element-wise. |
| `floor_divide(x1, x2)` | Return the largest integer smaller or equal to the division. |
| `negative(x)` | Numerical negative, element-wise. |
| `positive(x)` | Numerical positive, element-wise. |
| `power(x1, x2)` | First array elements raised to powers from second array, element-wise. |
| `remainder(x1, x2)` | Return element-wise remainder of division. |
| `mod(x1, x2)` | Return element-wise remainder of division (alias for remainder). |
| `fmod(x1, x2)` | Return the element-wise remainder of division (C-style). |
| `absolute(x)` | Calculate the absolute value element-wise. |
| `fabs(x)` | Compute the absolute values element-wise (for non-complex types). |
| `rint(x)` | Round elements of the array to the nearest integer. |
| `sign(x)` | Returns an element-wise indication of the sign of a number. |
| `heaviside(x1, x2)` | Compute the Heaviside step function. |
| `conj(x)` | Return the complex conjugate, element-wise. |
| `exp(x)` | Calculate the exponential of all elements in the input array. |
| `exp2(x)` | Calculate $2^p$ for all $p$ in the input array. |
| `log(x)` | Natural logarithm, element-wise. |
| `log2(x)` | Base-2 logarithm of x. |
| `log10(x)` | Return the base 10 logarithm of the input array, element-wise. |
| `expm1(x)` | Calculate `exp(x) - 1` for all elements in the array. |
| `log1p(x)` | Return the natural logarithm of one plus the input array, element-wise. |
| `sqrt(x)` | Return the non-negative square-root of an array, element-wise. |
| `square(x)` | Return the element-wise square of the input. |
| `cbrt(x)` | Return the cube-root of an array, element-wise. |
| `reciprocal(x)` | Return the reciprocal of the argument, element-wise. |
| `gcd(x1, x2)` | Returns the greatest common divisor of |x1| and |x2|. |
| `lcm(x1, x2)` | Returns the lowest common multiple of |x1| and |x2|. |

### 2. Trigonometric Functions
| Function | Description |
| :--- | :--- |
| `sin(x)` | Trigonometric sine, element-wise. |
| `cos(x)` | Trigonometric cosine, element-wise. |
| `tan(x)` | Compute tangent element-wise. |
| `arcsin(x)` | Inverse sine, element-wise. |
| `arccos(x)` | Trigonometric inverse cosine, element-wise. |
| `arctan(x)` | Trigonometric inverse tangent, element-wise. |
| `arctan2(y, x)` | Element-wise arc tangent of y/x choosing the quadrant correctly. |
| `hypot(x1, x2)` | Given the “legs” of a right triangle, return its hypotenuse. |
| `sinh(x)` | Hyperbolic sine, element-wise. |
| `cosh(x)` | Hyperbolic cosine, element-wise. |
| `tanh(x)` | Compute hyperbolic tangent element-wise. |
| `arcsinh(x)` | Inverse hyperbolic sine element-wise. |
| `arccosh(x)` | Inverse hyperbolic cosine element-wise. |
| `arctanh(x)` | Inverse hyperbolic tangent element-wise. |
| `deg2rad(x)` | Convert angles from degrees to radians. |
| `rad2deg(x)` | Convert angles from radians to degrees. |

### 3. Bit-twiddling Functions
| Function | Description |
| :--- | :--- |
| `bitwise_and(x1, x2)` | Compute the bitwise AND of two arrays element-wise. |
| `bitwise_or(x1, x2)` | Compute the bitwise OR of two arrays element-wise. |
| `bitwise_xor(x1, x2)` | Compute the bitwise XOR of two arrays element-wise. |
| `invert(x)` | Compute bitwise inversion, or bitwise NOT, element-wise. |
| `left_shift(x1, x2)` | Shift the bits of an integer to the left. |
| `right_shift(x1, x2)` | Shift the bits of an integer to the right. |

### 4. Comparison Functions
| Function | Description |
| :--- | :--- |
| `greater(x1, x2)` | Return the truth value of (x1 > x2) element-wise. |
| `greater_equal(x1, x2)` | Return the truth value of (x1 >= x2) element-wise. |
| `less(x1, x2)` | Return the truth value of (x1 < x2) element-wise. |
| `less_equal(x1, x2)` | Return the truth value of (x1 <= x2) element-wise. |
| `not_equal(x1, x2)` | Return (x1 != x2) element-wise. |
| `equal(x1, x2)` | Return (x1 == x2) element-wise. |
| `logical_and(x1, x2)` | Compute the truth value of x1 AND x2 element-wise. |
| `logical_or(x1, x2)` | Compute the truth value of x1 OR x2 element-wise. |
| `logical_xor(x1, x2)` | Compute the truth value of x1 XOR x2 element-wise. |
| `logical_not(x)` | Compute the truth value of NOT x element-wise. |
| `maximum(x1, x2)` | Element-wise maximum of array elements. |
| `minimum(x1, x2)` | Element-wise minimum of array elements. |
| `fmax(x1, x2)` | Element-wise maximum of array elements, ignoring NaNs. |
| `fmin(x1, x2)` | Element-wise minimum of array elements, ignoring NaNs. |

### 5. Floating Functions
| Function | Description |
| :--- | :--- |
| `isfinite(x)` | Test element-wise for finiteness (not infinity or NaN). |
| `isinf(x)` | Test element-wise for positive or negative infinity. |
| `isnan(x)` | Test element-wise for NaN and return result as a boolean array. |
| `isnat(x)` | Test element-wise for NaT (not a time) and return result as a boolean array. |
| `fabs(x)` | Compute the absolute values element-wise. |
| `signbit(x)` | Returns element-wise True where signbit is set (less than zero). |
| `copysign(x1, x2)` | Change the sign of x1 to that of x2, element-wise. |
| `nextafter(x1, x2)` | Return the next floating-point value after x1 towards x2, element-wise. |
| `spacing(x)` | Return the distance between x and the nearest adjacent number. |
| `modf(x)` | Return the fractional and integral parts of an array, element-wise. |
| `ldexp(x1, x2)` | Returns x1 * 2**x2, element-wise. |
| `frexp(x)` | Decompose the elements of x into mantissa and twos exponent. |
| `fmod(x1, x2)` | Return the element-wise remainder of division. |
| `floor(x)` | Return the floor of the input, element-wise. |
| `ceil(x)` | Return the ceiling of the input, element-wise. |
| `trunc(x)` | Return the truncated value of the input, element-wise. |

In [25]:
arr3 = np.random.randn(6)
arr3

array([ 1.97121632, -0.08876634,  0.80871035,  0.42203367,  0.29179732,
        0.96313384])

In [27]:
arr4 = np.random.randn(6)
arr4

array([-0.65447384,  0.38421726,  0.80944901, -0.42225866, -0.23822516,
        0.12999443])

In [28]:
np.multiply(arr3, arr4)  # element-wise multiplication

array([-1.29010951, -0.03410556,  0.65460978, -0.17820737, -0.06951346,
        0.12520203])

In [29]:
np.maximum(arr3, arr4)  # element-wise maximum

array([1.97121632, 0.38421726, 0.80944901, 0.42203367, 0.29179732,
       0.96313384])

## NumPy Element-Wise (Universal) Functions

### 1. Arithmetic Operations
| Function | Description |
| :--- | :--- |
| `add(x1, x2)` | Add arguments element-wise ($x_1 + x_2$). |
| `subtract(x1, x2)` | Subtract arguments element-wise ($x_1 - x_2$). |
| `multiply(x1, x2)` | Multiply arguments element-wise ($x_1 * x_2$). |
| `divide(x1, x2)` | Floating point division ($x_1 / x_2$). |
| `floor_divide(x1, x2)` | Integer (floor) division ($x_1 // x_2$). |
| `negative(x)` | Numerical negative ($-x$). |
| `positive(x)` | Numerical positive ($+x$). |
| `power(x1, x2)` | Raise first array elements to powers from second ($x_1^{x_2}$). |
| `remainder(x1, x2)` | Return element-wise remainder of division ($x_1 \% x_2$). |
| `mod(x1, x2)` | Alias for `remainder`. |
| `fmod(x1, x2)` | C-style remainder of division. |
| `divmod(x1, x2)` | Return element-wise quotient and remainder simultaneously. |
| `absolute(x)` / `abs(x)` | Calculate the absolute value. |
| `fabs(x)` | Absolute values (faster for non-complex types). |
| `rint(x)` | Round elements to the nearest integer. |
| `sign(x)` | Returns -1 for negative, 0 for zero, 1 for positive. |
| `heaviside(x1, x2)` | Compute the Heaviside step function. |
| `conj(x)` | Complex conjugate. |

### 2. Exponential & Logarithmic
| Function | Description |
| :--- | :--- |
| `exp(x)` | Exponential ($e^x$). |
| `exp2(x)` | Base-2 exponential ($2^x$). |
| `log(x)` | Natural logarithm ($\ln x$). |
| `log2(x)` | Base-2 logarithm. |
| `log10(x)` | Base-10 logarithm. |
| `expm1(x)` | Calculate $e^x - 1$ (more accurate for small $x$). |
| `log1p(x)` | Calculate $\ln(1 + x)$ (more accurate for small $x$). |
| `sqrt(x)` | Square root ($\sqrt{x}$). |
| `square(x)` | Square ($x^2$). |
| `cbrt(x)` | Cube root ($\sqrt[3]{x}$). |
| `reciprocal(x)` | Reciprocal ($1/x$). |

### 3. Trigonometric Functions
| Function | Description |
| :--- | :--- |
| `sin(x)` / `cos(x)` / `tan(x)` | Standard trigonometric functions (input in radians). |
| `arcsin(x)` / `arccos(x)` | Inverse sine and cosine. |
| `arctan(x)` | Inverse tangent. |
| `arctan2(y, x)` | Arc tangent of $y/x$ considering the quadrant. |
| `hypot(x1, x2)` | Given sides $x_1$ and $x_2$, return hypotenuse $\sqrt{x_1^2 + x_2^2}$. |
| `sinh(x)` / `cosh(x)` / `tanh(x)` | Hyperbolic functions. |
| `arcsinh(x)` / `arccosh(x)` | Inverse hyperbolic functions. |
| `deg2rad(x)` | Convert angles from degrees to radians. |
| `rad2deg(x)` | Convert angles from radians to degrees. |

### 4. Comparison & Logical
| Function | Description |
| :--- | :--- |
| `greater(x1, x2)` | $x_1 > x_2$. |
| `greater_equal(x1, x2)` | $x_1 \ge x_2$. |
| `less(x1, x2)` | $x_1 < x_2$. |
| `less_equal(x1, x2)` | $x_1 \le x_2$. |
| `not_equal(x1, x2)` | $x_1 \neq x_2$. |
| `equal(x1, x2)` | $x_1 == x_2$. |
| `logical_and(x1, x2)` | Element-wise AND. |
| `logical_or(x1, x2)` | Element-wise OR. |
| `logical_xor(x1, x2)` | Element-wise XOR. |
| `logical_not(x)` | Element-wise NOT. |
| `maximum(x1, x2)` | Element-wise max (propagates NaNs). |
| `minimum(x1, x2)` | Element-wise min (propagates NaNs). |
| `fmax(x1, x2)` | Element-wise max (ignores NaNs). |
| `fmin(x1, x2)` | Element-wise min (ignores NaNs). |

### 5. Floating Point & Bitwise
| Function | Description |
| :--- | :--- |
| `isnan(x)` | Returns True where value is NaN. |
| `isinf(x)` | Returns True where value is $\pm \infty$. |
| `isfinite(x)` | Returns True where value is not NaN or $\infty$. |
| `floor(x)` | Largest integer $i$ such that $i \le x$. |
| `ceil(x)` | Smallest integer $i$ such that $i \ge x$. |
| `trunc(x)` | Truncate towards zero. |
| `bitwise_and` / `or` / `xor` | Bitwise operations on integers. |
| `invert(x)` | Bitwise NOT. |
| `left_shift(x, n)` | Shift bits left by $n$ positions. |
| `right_shift(x, n)` | Shift bits right by $n$ positions. |