In [1]:
import numpy as np

In [10]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [11]:
# condition
cond = np.array([True, False, True, True, False])

In [12]:
# where 
result = np.where(cond, xarr, yarr) #if cond is True, take from xarr else from yarr
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [17]:
arr = np.random.randn(4, 4)
arr

array([[-1.06770204, -0.2942925 ,  0.45506484,  1.26852453],
       [-1.30423792,  0.25502259, -0.16551031, -1.03572206],
       [-0.47202125,  0.74219493,  0.09719763, -0.87367876],
       [-0.71515534,  0.20606197,  0.33248074, -0.54698169]])

In [ ]:
# where
results = np.where(arr > 0, 2, -2)

# if arr > 0:
#     results = 2
# else:
#     results = -2


results

array([[-2, -2,  2,  2],
       [-2,  2, -2, -2],
       [-2,  2,  2, -2],
       [-2,  2,  2, -2]])