## NumPy Statistical & Mathematical Methods

### 1. Basic Statistics (Order Statistics)
| Method | Description |
| :--- | :--- |
| `amin(a)` / `min(a)` | Return the minimum of an array or minimum along an axis. |
| `amax(a)` / `max(a)` | Return the maximum of an array or maximum along an axis. |
| `nanmin(a)` | Return minimum of an array, ignoring any NaNs. |
| `nanmax(a)` | Return maximum of an array, ignoring any NaNs. |
| `ptp(a)` | Peak-to-peak: Range of values (max - min) along an axis. |
| `percentile(a, q)` | Compute the q-th percentile of the data. |
| `nanpercentile(a, q)` | Compute the q-th percentile, ignoring NaNs. |
| `quantile(a, q)` | Compute the q-th quantile of the data. |
| `nanquantile(a, q)` | Compute the q-th quantile, ignoring NaNs. |

### 2. Averages and Variances
| Method | Description |
| :--- | :--- |
| `median(a)` | Compute the median along the specified axis. |
| `average(a, weights=...)` | Compute the weighted average. |
| `mean(a)` | Compute the arithmetic mean along the specified axis. |
| `std(a)` | Compute the standard deviation along the specified axis. |
| `var(a)` | Compute the variance along the specified axis. |
| `nanmedian(a)` | Compute the median, ignoring NaNs. |
| `nanmean(a)` | Compute the arithmetic mean, ignoring NaNs. |
| `nanstd(a)` | Compute the standard deviation, ignoring NaNs. |
| `nanvar(a)` | Compute the variance, ignoring NaNs. |

### 3. Sums, Products, and Differences
| Method | Description |
| :--- | :--- |
| `sum(a)` | Sum of array elements over a given axis. |
| `prod(a)` | Return the product of array elements over a given axis. |
| `nansum(a)` | Return the sum of array elements, treating NaNs as zeros. |
| `nanprod(a)` | Return the product of array elements, treating NaNs as ones. |
| `cumsum(a)` | Return the cumulative sum of the elements along a given axis. |
| `cumprod(a)` | Return the cumulative product of the elements along a given axis. |
| `nancumsum(a)` | Cumulative sum, treating NaNs as zeros. |
| `nancumprod(a)` | Cumulative product, treating NaNs as ones. |
| `diff(a)` | Calculate the n-th discrete difference along the given axis. |
| `ediff1d(a)` | The differences between consecutive elements of an array. |

### 4. Correlation and Histograms
| Method | Description |
| :--- | :--- |
| `corrcoef(x, y)` | Return Pearson product-moment correlation coefficients. |
| `cov(m, y)` | Estimate a covariance matrix. |
| `histogram(a, bins)` | Compute the histogram of a dataset. |
| `histogram2d(x, y)` | Compute the bi-dimensional histogram of two data samples. |
| `histogramdd(sample)` | Compute the multidimensional histogram of some data. |
| `bincount(x)` | Count number of occurrences of each value in array of non-negative ints. |
| `digitize(x, bins)` | Return the indices of the bins to which each value in input array belongs. |

In [3]:
import numpy as np

In [4]:
# data
arr = np.random.randn(5, 4)
arr

array([[-1.12530401,  0.66320493, -1.71863465,  0.89709622],
       [ 0.87643068,  0.18841154,  0.50721377, -0.23867194],
       [ 0.88042556,  0.45951673, -1.44816341, -1.38643154],
       [-0.68822941, -1.13091385,  1.16820176, -1.11672717],
       [ 1.4355897 ,  2.49510806, -1.53746968,  0.15874357]])

method `sum`

In [ ]:
arr.sum() # = np.sum(arr)

np.float64(-0.6606031374437847)

In [6]:
np.sum(arr)

np.float64(-0.6606031374437847)

In [11]:
arr.sum(axis=0)

array([ 1.37891252,  2.67532741, -3.02885222, -1.68599086])

In [12]:
arr.sum(axis=1)

array([-1.2836375 ,  1.33338406, -1.49465266, -1.76766867,  2.55197165])

In [13]:
np.mean(arr)

np.float64(-0.033030156872189236)

In [15]:
np.mean(arr, axis=0)

array([ 0.2757825 ,  0.53506548, -0.60577044, -0.33719817])

method `cunsom` 

In [16]:
data = np.arange(6)
data.cumsum()

array([ 0,  1,  3,  6, 10, 15])