In [1]:
import numpy as np

In [14]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
y = np.array([[7, 8], [9, 10], [11, 12]])
y

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [19]:
x.dot(y)

array([[ 58,  64],
       [139, 154]])

In [20]:
y.dot(x)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])