In [1]:
import numpy as np

| Canonical Python API name | Python API “C-like” name | Actual C type | Description |
| :--- | :--- | :--- | :--- |
| `numpy.bool` or `numpy.bool_` | N/A | `bool` (defined in `stdbool.h`) | Boolean (True or False) stored as a byte. |
| `numpy.int8` | `numpy.byte` | `signed char` | Platform-defined integer type with 8 bits. |
| `numpy.uint8` | `numpy.ubyte` | `unsigned char` | Platform-defined integer type with 8 bits without sign. |
| `numpy.int16` | `numpy.short` | `short` | Platform-defined integer type with 16 bits. |
| `numpy.uint16` | `numpy.ushort` | `unsigned short` | Platform-defined integer type with 16 bits without sign. |
| `numpy.int32` | `numpy.intc` | `int` | Platform-defined integer type with 32 bits. |
| `numpy.uint32` | `numpy.uintc` | `unsigned int` | Platform-defined integer type with 32 bits without sign. |
| `numpy.intp` | N/A | `ssize_t`/`Py_ssize_t` | Platform-defined integer of size `size_t`; used e.g. for sizes. |
| `numpy.uintp` | N/A | `size_t` | Platform-defined integer type capable of storing the maximum allocation size. |
| N/A | `'p'` | `intptr_t` | Guaranteed to hold pointers. Character code only (Python and C). |
| N/A | `'P'` | `uintptr_t` | Guaranteed to hold pointers without sign. Character code only (Python and C). |
| `numpy.int32` or `numpy.int64` | `numpy.long` | `long` | Platform-defined integer type with at least 32 bits. |
| `numpy.uint32` or `numpy.uint64` | `numpy.ulong` | `unsigned long` | Platform-defined integer type with at least 32 bits without sign. |
| N/A | `numpy.longlong` | `long long` | Platform-defined integer type with at least 64 bits. |
| N/A | `numpy.ulonglong` | `unsigned long long` | Platform-defined integer type with at least 64 bits without sign. |
| `numpy.float16` | `numpy.half` | N/A | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa. |
| `numpy.float32` | `numpy.single` | `float` | Platform-defined single precision float: typically sign bit, 8 bits exponent, 23 bits mantissa. |
| `numpy.float64` | `numpy.double` | `double` | Platform-defined double precision float: typically sign bit, 11 bits exponent, 52 bits mantissa. |
| `numpy.float96` or `numpy.float128` | `numpy.longdouble` | `long double` | Platform-defined extended-precision float. |
| `numpy.complex64` | `numpy.csingle` | `float complex` | Complex number, represented by two single-precision floats (real and imaginary components). |
| `numpy.complex128` | `numpy.cdouble` | `double complex` | Complex number, represented by two double-precision floats (real and imaginary components). |
| `numpy.complex192` or `numpy.complex256` | `numpy.clongdouble` | `long double complex` | Complex number, represented by two extended-precision floats (real and imaginary components). |

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # this will create an array of floats
arr1

array([1., 2., 3.])

In [3]:
arr2 = np.array([1, 2, 3], dtype=np.int32) # int32 will create an array of integers
arr2

array([1, 2, 3], dtype=int32)

`dytype` method

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr2.dtype

dtype('int32')

In [6]:
arr = np.array([1, 2, 3, 4]) # int64
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int64')

changing datatype

`astype` method

In [8]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [9]:
data = np.array([3.4, 5.7, 1.8, 4]) # float64
data.dtype

dtype('float64')

In [16]:
int_data = data.astype(np.int64)
int_data.dtype

dtype('int64')

In [13]:
int_data

array([3, 5, 1, 4])