In [11]:
import numpy as np

In [27]:
arr = np.arange(10, 200, 10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [28]:
arr[3:5]

array([40, 50])

In [29]:
sliced_arr = arr[3:8]
sliced_arr

array([40, 50, 60, 70, 80])

In [23]:
sliced_arr[:] = 0
sliced_arr

array([0, 0, 0, 0, 0])

copy

In [30]:
arr2 = np.arange(10, 200, 10)
arr2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [32]:
sliced_arr2 = arr2[3:8].copy()
sliced_arr2[:] = 0
sliced_arr2

array([0, 0, 0, 0, 0])

In [33]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [38]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # 2D array (3x3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr2d[1, 1]  # Accessing the element at row index 1 and column index 1

np.int64(5)

Slicing elements from 2D aray

In [50]:
sl_arr2d = arr2d[2, 1:3]  # Slicing the second row, columns 1 to 2
sl_arr2d

array([8, 9])

# 3D array

In [52]:
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
arr3d[0][1, 1]

np.int64(4)

In [54]:
arr3d[1][2, 1:]

array([16, 17])

In [56]:
arr3d[2][0][1:3]

array([19, 20])