In [2]:
import numpy as np

In [22]:
# Names

names = np.array(['Eve', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'])
names

array(['Eve', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
      dtype='<U7')

In [23]:
# data
data = np.random.randn(7, 4)  # 7 rows, 4 columns
data

array([[-0.31244053, -1.56327895,  0.3732718 , -0.59254122],
       [ 1.34768499, -1.67611731,  0.08702683,  0.56371567],
       [ 1.23770626,  1.03747394, -0.49138221,  0.15288644],
       [-0.03607632, -0.0358487 ,  0.91980225, -0.03400185],
       [ 0.03671391, -0.18253225, -0.73209418, -0.99402851],
       [ 2.14003266, -0.3781778 ,  1.62845393, -0.16259068],
       [-0.37706694,  0.85202129,  1.03773224, -0.81988035]])

In [19]:
names == 'Eve'  # Boolean array where names are 'Eve'

array([ True, False, False, False,  True, False, False])

In [27]:
data[names == 'Eve']  # Select rows where names are 'Eve'

array([[-0.31244053, -1.56327895,  0.3732718 , -0.59254122],
       [ 0.03671391, -0.18253225, -0.73209418, -0.99402851]])

In [21]:
data[names != 'Eve']  # Select rows where names are not 'Eve'

array([[ 1.96024874, -0.46638906,  1.27717053,  0.03714949],
       [ 1.61418968, -1.63838852, -0.71600661,  0.1817765 ],
       [-0.5855728 , -1.44651573, -0.43882525,  1.78182697],
       [-0.874431  , -2.68543009,  1.07888935, -0.32398667],
       [ 0.40134001, -1.53093596,  0.8364095 ,  0.03342089]])

In [29]:
print(names)
print(data)

['Eve' 'Bob' 'Charlie' 'David' 'Eve' 'Frank' 'Grace']
[[-0.31244053 -1.56327895  0.3732718  -0.59254122]
 [ 1.34768499 -1.67611731  0.08702683  0.56371567]
 [ 1.23770626  1.03747394 -0.49138221  0.15288644]
 [-0.03607632 -0.0358487   0.91980225 -0.03400185]
 [ 0.03671391 -0.18253225 -0.73209418 -0.99402851]
 [ 2.14003266 -0.3781778   1.62845393 -0.16259068]
 [-0.37706694  0.85202129  1.03773224 -0.81988035]]


In [30]:
mask = (names == 'Eve') | (names == 'Bob')  # Combine conditions
data[mask]  # 'Eve' or 'Bob'

array([[-0.31244053, -1.56327895,  0.3732718 , -0.59254122],
       [ 1.34768499, -1.67611731,  0.08702683,  0.56371567],
       [ 0.03671391, -0.18253225, -0.73209418, -0.99402851]])

In [31]:
data

array([[-0.31244053, -1.56327895,  0.3732718 , -0.59254122],
       [ 1.34768499, -1.67611731,  0.08702683,  0.56371567],
       [ 1.23770626,  1.03747394, -0.49138221,  0.15288644],
       [-0.03607632, -0.0358487 ,  0.91980225, -0.03400185],
       [ 0.03671391, -0.18253225, -0.73209418, -0.99402851],
       [ 2.14003266, -0.3781778 ,  1.62845393, -0.16259068],
       [-0.37706694,  0.85202129,  1.03773224, -0.81988035]])

In [32]:
data[data < 0] = 0 
data

array([[0.        , 0.        , 0.3732718 , 0.        ],
       [1.34768499, 0.        , 0.08702683, 0.56371567],
       [1.23770626, 1.03747394, 0.        , 0.15288644],
       [0.        , 0.        , 0.91980225, 0.        ],
       [0.03671391, 0.        , 0.        , 0.        ],
       [2.14003266, 0.        , 1.62845393, 0.        ],
       [0.        , 0.85202129, 1.03773224, 0.        ]])