In [1]:
import numpy as np

In [11]:
A = np.arange(6).reshape((2, 3))
A

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
A.T

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
A

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
A.swapaxes(1, 0) # Swap axes 0 and 1

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
A

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
np.dot(A, A.T)  # Matrix multiplication. AA^T

array([[ 9, 12, 15],
       [12, 17, 22],
       [15, 22, 29]])