In [2]:
import numpy as np

In [10]:
# data
arr1 = np.arange(6).reshape(2, 3)
arr2 = np.arange(6, 12).reshape(2, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
arr2 + arr1

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr1**3

array([[  0,   1,   8],
       [ 27,  64, 125]])

In [16]:
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])